version: "3.9"

services:
  web_app:
    image: node:18.18.2-slim
    container_name: chrsolr-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
