import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs"
import { type NextPage } from "next"
import Head from "next/head"

import { api } from "~/utils/api"

const Home: NextPage = () => {
  const user = useUser()
  const { data: currentUserData } = api.users.getById.useQuery({
    userId: "clfmxnryf00008nk0vsot29nj",
  })
  console.log(currentUserData)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full max-w-3xl justify-center">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && <SignOutButton />}
        </div>
      </main>
    </>
  )
}

export default Home
