import { SignInButton, SignOutButton } from '@clerk/nextjs'
import { type NextPage } from 'next'
import Head from 'next/head'
import { useContext } from 'react'
import { UserContext } from '~/contexts/UserContextProvider'

const Home: NextPage = () => {
  const { isSignedIn } = useContext(UserContext)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full max-w-3xl justify-center">
        <div>
          {!isSignedIn && <SignInButton />}
          {isSignedIn && <SignOutButton />}
        </div>
      </main>
    </>
  )
}

export default Home
